<a href="https://colab.research.google.com/github/PrathamK03/python-program/blob/main/Exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
mnist = fetch_openml('mnist_784')
x=mnist.data
y=mnist.target

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#scaler=StandardScaler()
#x_train=scaler.fit_transform(x_train)
#x_test=scaler.transform(x_test)

In [ ]:
mlp=MLPClassifier(hidden_layer_sizes=(64,32),max_iter=1000,random_state=0)

In [ ]:
mlp.fit(x_train,y_train)
y_pred=mlp.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.9603571428571429


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1387
           1       0.98      0.99      0.98      1580
           2       0.96      0.97      0.96      1443
           3       0.96      0.94      0.95      1435
           4       0.95      0.97      0.96      1350
           5       0.93      0.96      0.95      1231
           6       0.98      0.96      0.97      1387
           7       0.98      0.95      0.96      1458
           8       0.94      0.96      0.95      1368
           9       0.94      0.94      0.94      1361

    accuracy                           0.96     14000
   macro avg       0.96      0.96      0.96     14000
weighted avg       0.96      0.96      0.96     14000



In [ ]:
print(confusion_matrix(y_test,y_pred))

[[1342    0    5    1    4    7   12    1   12    3]
 [   0 1559    5    5    2    2    2    2    3    0]
 [   0    4 1394   12    3    1    4    7   16    2]
 [   1    7   19 1350    0   26    0    7   18    7]
 [   1    2    2    1 1306    0    4    6    6   22]
 [   2    0    1   15    0 1187    7    0   10    9]
 [   7    0    1    0   19   23 1325    1   10    1]
 [   2   10   16    8   12    3    0 1385    1   21]
 [   1   10    3    8    7   18    0    0 1311   10]
 [   2    5    6    9   25   10    0    8   10 1286]]
