In [ ]:
# Performing matrix operations using array.

import numpy as np

x1=[]
x=int(input('enter the number of elements:'))
for i in range(0,x):
  x=int(input())
  x1.append(x)
print(x1)

x2=[]
y=int(input('enter the number of elements:'))
for i in range(0,y):
  y=int(input())
  x2.append(y)
print(x2)

x3=[]
print('1:Addition')
print('2:Multiplication')
print('3:Substraction')
print('4:Division')
z=int(input('Enter the operation you want to perform:'))

if(z == 1):
  x3=np.add(x1,x2)
  print(x3)

elif(z == 2):
  x3=np.multiply(x1,x2)
  print(x3)

elif(z ==3):
  x3=np.subtract(x1,x2)
  print(x3)

elif(z == 4):
  x3=np.divide(x1,x2)
  print(x3)

else:
  print('invalid choice')

Add: [[ 6  8]
 [10 12]]
Sub: [[-4 -4]
 [-4 -4]]
Mul: [[ 5 12]
 [21 32]]
DIv: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
import numpy as np
a= np.array([1,23,4,5,66])
b=np.array([23,2,44,5,6])
print("a=",a)
print("b=",b)
c=np.intersect1d(a,b)
print("common elements from a and b numpy arrays are:",c)

a= [ 1 23  4  5 66]
b= [23  2 44  5  6]
common elements from a and b numpy arrays are: [ 5 23]


In [ ]:
# Getting common items between two arrays.

import numpy as np

x=np.array([1,2,3,4])
y=np.array([5,2,7,8])

#for i in range(x[0],x[4]):
if(x[0]) == (y[0]):
  print('same values for 0th position')
else:
  print('not the same values for 0th position')
if(x[1]) == (y[1]):
  print('same values for 1st position')
else:
  print('not the same values for 1st position')
if(x[2]) == (y[2]):
  print('same values for 2nd position')
else:
  print('not the same values for 2nd position')
if(x[3]) == (y[3]):
  print('same values for 3rd position')
else:
  print('not the same values for 3rd position')

not the same values for 0th position
same values for 1st position
not the same values for 2nd position
not the same values for 3rd position


In [ ]:
import numpy as np
arr=np.array(range(1,10))
print("array=",arr)
print("odd elements of the array are:",arr[arr%2!=0])

array= [1 2 3 4 5 6 7 8 9]
odd elements of the array are: [1 3 5 7 9]


In [ ]:
# Extracting all odd numbers from an array.

import numpy as np

x=np.array([1,2,3,4])

if(x[0]%2!=0):
  print('it is an odd number:',x[0])
if(x[1]%2!=0):
  print('it is an odd number:',x[1])
if(x[2]%2!=0):
  print('it is an odd number:',x[2])
if(x[3]%2!=0):
  print('it is an odd number',x[3])

it is an odd number: 1
it is an odd number: 3


In [ ]:
import numpy as np
a = np.array([11,12,23,34,55,66])
b = np.array([11,22,23,32,56,60])
print("position where elements of the array match:")
np.where(a==b)

position where elements of the array match:


(array([0, 2]),)

In [ ]:
# Get positions where elements of two arrays match.

import numpy as np

x=np.array([1,2,3,4])
y=np.array([2,4,6,8])

if(x[0]) == (y[0]):
  print('it is the same:',x[0])
if(x[0]) == (y[1]):
  print('it is the same:',x[0])
if(x[0]) == (y[2]):
  print('it is the same:',x[0])
if(x[0]) == (y[3]):
  print('it is the same:',x[0])

if(x[1]) == (y[0]):
  print('it is the same:',x[1])
if(x[1]) == (y[1]):
  print('it is the same:',x[1])
if(x[1]) == (y[2]):
  print('it is the same:',x[1])
if(x[1]) == (y[3]):
  print('it is the same:',x[1])

if(x[2]) == (y[0]):
  print('it is the same:',x[2])
if(x[2]) == (y[1]):
  print('it is the same:',x[2])
if(x[2]) == (y[2]):
  print('it is the same:',x[2])
if(x[2]) == (y[3]):
  print('it is the same:',x[2])

if(x[3]) == (y[0]):
  print('it is the same:',x[3])
if(x[3]) == (y[1]):
  print('it is the same:',x[3])
if(x[3]) == (y[2]):
  print('it is the same:',x[3])
if(x[3]) == (y[3]):
  print('it is the same:',x[3])

it is the same: 2
it is the same: 4


In [ ]:
import numpy as np
arr=np.array(range(1,50))
start = np.searchsorted(arr, 10, 'left')
end = np.searchsorted(arr, 20, 'right')
result = np.arange(start, end)
print("the elements in the given range are:",result)

the elements in the given range are: [ 9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Get positions where elements of two arrays match.

import numpy as np

x=np.array([1,2,3,4])
y=np.array([2,4,6,8])
z=np.where(x==y)
print(z)
for i in range(0,4):
  for j in range(0,4):
    if(x[i]) == (y[j]):
      print('')
print(y[j],x[i])

(array([], dtype=int64),)


8 4


In [ ]:
import numpy as np
bool_arr = np.array([1, 50, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [ ]:
# Create a boolean array.

import numpy as np

x=np.array([True,False,True,False])
print(x)

[ True False  True False]


In [ ]:
# Create a 2D array containing random floats between 5 and 10.

import numpy
#random_float_array = numpy.random.uniform(5,10, size=(2, 2))
random_float_array = numpy.random.uniform(5,10,size=(2,4))
print(random_float_array)


[[8.16658718 6.72606734 9.99254425 9.17667779]
 [6.52935874 5.89453585 9.51887968 9.33072856]]


In [ ]:
import numpy as np
my_array = np.arange(8).reshape(2, 4)
print("Original array:")
print(my_array)
my_array[[0,1],:] = my_array[[1,0],:]
print("\nAfter swapping arrays:")
print(my_array)

Original array:
[[0 1 2 3]
 [4 5 6 7]]

After swapping arrays:
[[4 5 6 7]
 [0 1 2 3]]


In [ ]:
# Swap two rows in a 2D array.

import numpy as np

x=np.array([1,2,3,4])
temp=0

temp=x[0]
x[0]=x[3]
x[3]=temp

temp=x[1]
x[1]=x[2]
x[2]=temp

print(x)

[4 3 2 1]


In [ ]:
# Swap two columns in a 2D array.

import numpy as np
my_array = np.arange(8).reshape(2, 4)
print("Original array:")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("\nAfter swapping arrays:")
print(my_array)

Original array:
[[0 1 2 3]
 [4 5 6 7]]

After swapping arrays:
[[1 0 2 3]
 [5 4 6 7]]
