Pratham Kumbhare (IT3221) (T1-Batch)

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [ ]:
x=10
y=np.sqrt(x)
z=np.mean(y)
print(y)
print(z)

3.1622776601683795
3.1622776601683795


In [ ]:
arr1=np.array([[2,4,6,8],[1,2,3,4]])
print(arr1)
print("the number of dimentions in an array are",arr1.ndim)
print("the shape of the array is",arr1.shape)
print("the size of the array is",arr1.size)
print("the data type of the array is",arr1.dtype)

[[2 4 6 8]
 [1 2 3 4]]
the number of dimentions in an array are 2
the shape of the array is (2, 4)
the size of the array is 8
the data type of the array is int64


In [ ]:
x=np.array([[2,2,2,2],[5,5,5,5]])
a=np.arange(0,30,5)
print(a)

[ 0  5 10 15 20 25]


In [ ]:
y=np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]])
print("the shape is",y.shape)
newy=y.reshape(2,2,3)
print(newy)

the shape is (3, 4)
[[[0 0 0]
  [0 1 1]]

 [[1 1 2]
  [2 2 2]]]


In [ ]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [ ]:
b=np.arange(5)
print(b)

[0 1 2 3 4]


In [ ]:
c=np.arange(5,10)
print(c)

[5 6 7 8 9]


In [ ]:
d=np.random.rand(10)
print(d)

[0.85776839 0.69221951 0.6397012  0.09785724 0.5723379  0.63191698
 0.61540674 0.95789196 0.91849456 0.41956766]


In [ ]:
e=np.empty((2,2))
print(e)

[[0. 0.]
 [0. 0.]]


In [ ]:
f=np.random.rand(3,3)
print(f)

[[0.63891969 0.21930639 0.31970214]
 [0.87445945 0.54899894 0.62411695]
 [0.15394077 0.91770359 0.59846447]]


In [ ]:
g=np.array([1,2,3,4])
h=np.array([0.1,0.2,0.3,0.4])
i=np.array([1+2j,5-1j,6+3j])
print(g.dtype)
print(h.dtype)
print(i.dtype)


int64
float64
complex128


In [ ]:
j=g.astype('float')
print(g)
print(j)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
np.save('test.npy',g)

In [ ]:
k=np.load('test.npy')

In [ ]:
print(k)

[1 2 3 4]


In [ ]:
np.savetxt('test1.txt',h)
l=np.loadtxt('test1.txt')
print(l)

[0.1 0.2 0.3 0.4]


In [ ]:
print(h[0])
print(h[1])

0.1
0.2


In [ ]:
h[0]=1.2
print(h)

[1.2 0.2 0.3 0.4]


In [ ]:
import numpy as np
ar=np.array([
    [1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]
    ])
print(ar)
print("")
print("The data type of this given array is",ar.dtype)
print("The size of this given array is",ar.size)
print("The shape of this given array is",ar.shape)
print("The dimentions of this given array is",ar.ndim)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]

The data type of this given array is int64
The size of this given array is 25
The shape of this given array is (5, 5)
The dimentions of this given array is 2


In [ ]:
abc=np.arange(0,100,5)
print(abc)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
xyz=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
print("The shape of this given array is",xyz.shape)

The shape of this given array is (4, 4)
