In [ ]:
#One Dimentional Tensors

import numpy as np
tensor_1d=([1,2,3,4,5])
print(tensor_1d)
print(tensor_1d[0])

[1, 2, 3, 4, 5]
1


In [ ]:
#Two Dimentional Tensors

import numpy as np
tensor_2d=([(1,1,1,1),(2,2,2,2),(3,3,3,3),(4,4,4,4)])
print(tensor_2d)

[(1, 1, 1, 1), (2, 2, 2, 2), (3, 3, 3, 3), (4, 4, 4, 4)]


In [1]:
#Tensor Handling and Manipulations

import numpy as np
import tensorflow as tf
matrix1=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]],dtype='int32')
matrix2=np.array([[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]],dtype='int32')
print(matrix1)
print(matrix2)
#matrix1=tf.constant(matrix1)
#matrix2=tf.constant(matrix2)
matrix_product=tf.matmul(matrix1,matrix2)
matrix_sum=tf.add(matrix1,matrix2)
matrix3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype='float32')
print(matrix3)
#with tf.Session() as sess:
#  result1=sess.run(matrix_product)
#  result2=sess.run(matrix_sum)
#  print(result1)
#  print(result2)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[[5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
